# Generated by Django 3.2 on 2021-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_historicaldatadistribution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDataCollection',
        ),
    ]
