# Generated by Django 3.2 on 2021-04-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_historicaldatacollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFinesExport',
        ),
    ]
