# Generated by Django 3.2 on 2021-04-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0004_delete_studentfinesexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDistributionArchive',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('student_first_name', models.CharField(max_length=25, null=True)),
                ('student_grade', models.CharField(max_length=2, null=True)),
                ('student_last_name', models.CharField(max_length=25, null=True)),
                ('parent_address', models.CharField(max_length=150, null=True)),
                ('parent_agreement', models.BooleanField()),
                ('parent_email', models.EmailField(max_length=254, null=True)),
                ('parent_name', models.CharField(max_length=50, null=True)),
                ('parent_phone', models.CharField(max_length=15, null=True)),
                ('parent_signature', models.CharField(max_length=75, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('payment_complete', models.BooleanField(default=0)),
                ('promotion_code', models.CharField(blank=True, max_length=25, null=True)),
                ('student_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
            ],
            options={
                'verbose_name': 'Distribution Data',
                'verbose_name_plural': 'Distribution Data',
                'ordering': ['student_id', 'student_first_name', 'student_last_name'],
            },
        ),
    ]
