# Generated by Django 3.2 on 2021-04-22 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_datadistributionarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadistributionarchive',
            name='student_id',
            field=models.CharField(max_length=15, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='datadistributionarchive',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
