# Generated by Django 3.2 on 2021-05-04 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('users', '0006_auto_20210422_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinesExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Paid'), ('UP', 'Unpaid')], default='UP', max_length=2, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_export', to='inventory.device')),
                ('fine_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_subtype_export', to='inventory.finesubtypes')),
                ('fine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_type_export', to='inventory.finetypes')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_export', to='inventory.location')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fine_export', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Fine',
                'verbose_name_plural': 'Student Fines',
            },
        ),
    ]
