# Generated by Django 3.2 on 2021-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_datacollection_device_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='device_bin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
