# Generated by Django 3.2 on 2021-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_datacollection_device_bin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalStudentPrograms',
        ),
    ]
