# Generated by Django 3.2 on 2021-05-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_historicalstudentprograms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprograms',
            options={'ordering': ['created'], 'verbose_name': 'Student Program', 'verbose_name_plural': 'Student Programs'},
        ),
    ]
