# Generated by Django 3.2 on 2021-05-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_studentprograms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='is_remote',
            field=models.BooleanField(default=0),
        ),
    ]
