# Generated by Django 3.2 on 2021-05-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_historicalstudent_is_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
    ]
