# Generated by Django 3.2.5 on 2021-07-09 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_calendlyevent_event_name'),
        ('users', '0015_alter_historicalstudent_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAppointments',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField()),
                ('scheduler_name', models.CharField(max_length=50)),
                ('scheduler_email', models.CharField(max_length=250)),
                ('scheduler_phone', models.CharField(max_length=25)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.calendlyevent')),
                ('student_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_appointment', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Appointment',
                'verbose_name_plural': 'Student Appointments',
            },
        ),
    ]
