# Generated by Django 3.2.5 on 2021-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_studentappointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicall5qdistribution',
            name='iiq_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='l5qdistribution',
            name='iiq_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
