# Generated by Django 3.2.5 on 2021-07-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210709_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentappointments',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='studentappointments',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentappointments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_appointment', to='users.student'),
        ),
    ]
