# Generated by Django 3.2.8 on 2021-10-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_historicalstudentmodel_studentmodel_studentstatuses_studenttypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTypes',
        ),
    ]
