# Generated by Django 3.2.8 on 2021-10-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_studenttypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudentmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='type',
        ),
    ]
