# Generated by Django 3.2.8 on 2021-10-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20211026_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalStudentModel',
        ),
    ]
