# Generated by Django 3.2.8 on 2021-10-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_locationcode'),
        ('users', '0026_delete_historicalstudentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='location_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.locationcode'),
        ),
    ]
