# Generated by Django 3.2.8 on 2021-11-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_locationcode'),
        ('users', '0029_auto_20211101_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDeviceOwnership',
            new_name='DeviceOwnership',
        ),
        migrations.AlterModelOptions(
            name='deviceownership',
            options={'verbose_name': 'Device Ownership', 'verbose_name_plural': 'Devices Ownership'},
        ),
        migrations.CreateModel(
            name='HistoricalDeviceOwnership',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.studentmodel')),
            ],
            options={
                'verbose_name': 'historical Device Ownership',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
