# Generated by Django 4.0a1 on 2021-11-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_devicehistorydata_author_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0030_auto_20211102_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDeviceOwnership',
            new_name='HistoricalStudentDeviceOwnership',
        ),
        migrations.RenameModel(
            old_name='DeviceOwnership',
            new_name='StudentDeviceOwnership',
        ),
    ]
