# Generated by Django 3.2.8 on 2021-11-09 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_devicehistorydata_author_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0031_rename_historicaldeviceownership_historicalstudentdeviceownership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstudentdeviceownership',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Student: Device Ownership'},
        ),
        migrations.AlterModelOptions(
            name='studentdeviceownership',
            options={'verbose_name': 'Student: Device Ownership', 'verbose_name_plural': 'Student: Devices Ownership'},
        ),
        migrations.CreateModel(
            name='StudentChargerOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('charger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.charger')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentmodel')),
            ],
            options={
                'verbose_name': 'Student: Charger Ownership',
                'verbose_name_plural': 'Student: Charger Ownership',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudentChargerOwnership',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('charger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.charger')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.studentmodel')),
            ],
            options={
                'verbose_name': 'historical Student: Charger Ownership',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
