# Generated by Django 3.2.8 on 2021-11-22 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_devicehistorydata_author_id'),
        ('users', '0033_auto_20211110_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('iiq_id', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=datetime.datetime(1988, 6, 1, 8, 0))),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentstatuses')),
            ],
            options={
                'verbose_name': 'Staff (Ed-Fi)',
                'verbose_name_plural': 'Staff (Ed-Fi)',
                'ordering': ['id', 'name'],
            },
        ),
    ]
