# Generated by Django 4.0a1 on 2021-11-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_staffmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudenttransfers',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.studentmodel'),
        ),
        migrations.AlterField(
            model_name='studenttransfers',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_transfer', to='users.studentmodel'),
        ),
    ]
