# Generated by Django 4.0a1 on 2021-11-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_historicalstudenttransfers_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalStudentTransfers',
        ),
    ]
