# Generated by Django 3.2.8 on 2021-12-15 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_devicehistorydata_author_id'),
        ('users', '0037_delete_historicalstudenttransfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudentModel',
            fields=[
                ('id', models.CharField(db_index=True, max_length=15, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('iiq_id', models.UUIDField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=datetime.datetime(1988, 6, 1, 8, 0))),
                ('history_change_reason', models.TextField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('remote', models.BooleanField(default=0)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location')),
                ('location_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.locationcode')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.studentrole')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.studentstatuses')),
            ],
            options={
                'verbose_name': 'historical Student (Ed-Fi)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
