# Generated by Django 3.2.8 on 2022-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_historicalstaffmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentmodel',
            name='withdraw_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='withdraw_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
