# Generated by Django 3.2.8 on 2022-01-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20220119_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentmodel',
            name='withdraw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='withdraw_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
