# Generated by Django 3.2.8 on 2022-02-27 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_auto_20220201_1417'),
        ('users', '0041_auto_20220119_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDataCollection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=36, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('student_next_grade', models.CharField(max_length=2, null=True)),
                ('parent_address', models.CharField(max_length=150, null=True)),
                ('parent_email', models.EmailField(max_length=254, null=True)),
                ('parent_name', models.CharField(max_length=50, null=True)),
                ('parent_phone', models.CharField(max_length=15, null=True)),
                ('device_return_type', models.CharField(choices=[('DRSR', 'Device Returned (Summer Refresh)'), ('DRNR', 'Device Returned (Not Returning)')], default='DRSR', max_length=4)),
                ('device_damage_present', models.BooleanField(default=0)),
                ('device_damage_dd', models.BooleanField(default=0)),
                ('device_damage_edd', models.BooleanField(default=0)),
                ('device_damage_lis', models.BooleanField(default=0)),
                ('device_damage_cs', models.BooleanField(default=0)),
                ('device_damage_tnc', models.BooleanField(default=0)),
                ('device_damage_tc', models.BooleanField(default=0)),
                ('device_damage_ms', models.BooleanField(default=0)),
                ('device_damage_ld', models.BooleanField(default=0)),
                ('device_damage_mkr', models.BooleanField(default=0)),
                ('device_damage_mku', models.BooleanField(default=0)),
                ('device_damage_bci', models.BooleanField(default=0)),
                ('device_damage_ccd', models.BooleanField(default=0)),
                ('device_bin', models.CharField(blank=True, max_length=10, null=True)),
                ('charger_return_type', models.CharField(choices=[('CR', 'Charger Returned'), ('CNR', 'Charger Not Returned'), ('CNRSR', 'Charger Not Returned (Summer Refresh)')], default='CR', max_length=5)),
                ('charger_damage_present', models.BooleanField(default=0)),
                ('charger_dh', models.BooleanField(default=0)),
                ('charger_ex', models.BooleanField(default=0)),
                ('charger_co', models.BooleanField(default=0)),
                ('charger_br', models.BooleanField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_next_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
            ],
            options={
                'verbose_name': 'Device Collection',
                'verbose_name_plural': 'Device Collections',
            },
        ),
    ]
