# Generated by Django 3.2.8 on 2022-02-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20220201_1417'),
        ('users', '0042_newdatacollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdatacollection',
            name='user_id',
        ),
        migrations.AddField(
            model_name='newdatacollection',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device'),
        ),
        migrations.AddField(
            model_name='newdatacollection',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentmodel'),
        ),
    ]
