# Generated by Django 4.0.2 on 2022-05-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_auto_20220201_1417'),
        ('users', '0043_auto_20220227_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModelPrograms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.personprograms')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentmodel')),
            ],
            options={
                'verbose_name': 'Student Program Enrollment',
                'verbose_name_plural': 'Student Program Enrollments',
                'ordering': ['created'],
            },
        ),
    ]
