# Generated by Django 3.2.8 on 2022-06-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_historicalstudentmodel_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentappointments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_appointment', to='users.studentmodel'),
        ),
    ]
