# Generated by Django 4.0.6 on 2022-07-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_studentappointments_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicall5qdistribution',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.studentmodel'),
        ),
        migrations.AlterField(
            model_name='l5qdistribution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentmodel'),
        ),
    ]
