# Generated by Django 4.0.6 on 2022-07-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_historicall5qdistribution_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalL5QDistribution',
        ),
    ]
