# Generated by Django 4.0.6 on 2022-07-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_delete_historicall5qdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l5qdistribution',
            name='iiq_ticket_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
