# Generated by Django 3.2.13 on 2022-09-26 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0050_alter_l5qdistribution_iiq_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModelIDLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentmodel')),
            ],
            options={
                'verbose_name': 'Student: ID Log',
                'verbose_name_plural': 'Student: ID Logs',
            },
        ),
    ]
