# Generated by Django 3.2.8 on 2023-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20230207_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicServicesOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_services_opt_out', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_email', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_id_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands')], max_length=2)),
                ('parent_id_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_1_parent_1_name', models.CharField(max_length=50)),
                ('fam_1_parent_1_cell_phone', models.CharField(max_length=15)),
                ('fam_1_parent_1_daytime_phone', models.CharField(max_length=15)),
                ('fam_1_parent_2_name', models.CharField(max_length=50)),
                ('fam_1_parent_2_cell_phone', models.CharField(max_length=15)),
                ('fam_1_parent_2_daytime_phone', models.CharField(max_length=15)),
                ('fam_1_email', models.CharField(max_length=50)),
                ('fam_1_residence', models.CharField(max_length=256)),
                ('fam_1_mailing', models.CharField(max_length=256)),
                ('fam_2_parent_1_name', models.CharField(max_length=50)),
                ('fam_2_parent_1_cell_phone', models.CharField(max_length=15)),
                ('fam_2_parent_1_daytime_phone', models.CharField(max_length=15)),
                ('fam_2_parent_2_name', models.CharField(max_length=50)),
                ('fam_2_parent_2_cell_phone', models.CharField(max_length=15)),
                ('fam_2_parent_2_daytime_phone', models.CharField(max_length=15)),
                ('fam_2_email', models.CharField(max_length=50)),
                ('fam_2_residence', models.CharField(max_length=256)),
                ('fam_2_mailing', models.CharField(max_length=256)),
                ('custody_paperwork', models.BooleanField(choices=[('Yes', True), ('No', False)])),
                ('pickup_1_name', models.CharField(max_length=50)),
                ('pickup_1_phone', models.CharField(max_length=15)),
                ('pickup_1_relationship', models.CharField(max_length=20)),
                ('pickup_2_name', models.CharField(max_length=50)),
                ('pickup_2_phone', models.CharField(max_length=15)),
                ('pickup_2_relationship', models.CharField(max_length=20)),
                ('pickup_3_name', models.CharField(max_length=50)),
                ('pickup_3_phone', models.CharField(max_length=15)),
                ('pickup_3_relationship', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HealthScreeningsOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_screenings_opt_out', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaParentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_choice_level', models.CharField(choices=[(1, 'Level 1: Open Access: Students are able to select books at their discretion. There are some levels of books that require parent permission before a student can check them out.'), (2, 'Level 2: Limited Access: Families may submit a list of up to 5 books that students are NOT allowed to check-out. Outside of the 5 books that students are NOT allowed to check-out, students have the same access to Level 1.'), (3, 'Level 3: Pre-Approval: A parent/guardian will pre-approve all books before a student checks them out.')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.BooleanField(choices=[('Yes', True), ('No', False)])),
                ('allergic_to', models.CharField(max_length=256)),
                ('glasses_or_contacts', models.BooleanField(choices=[('Yes', True), ('No', False)])),
                ('hearing_aids', models.BooleanField(choices=[('Yes', True), ('No', False)])),
                ('physician_name', models.CharField(max_length=50)),
                ('physician_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
