# Generated by Django 3.2.8 on 2023-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_clinicservicesoptout_contactvalidation_emergencycontactinfo_healthscreeningsoptout_mediaparentchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClinicServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=10)),
                ('basic_first_aid', models.CharField(max_length=7)),
                ('minor_wound_care', models.CharField(max_length=7)),
                ('minor_eye_irritation', models.CharField(max_length=7)),
                ('minor_bites_and_stings', models.CharField(max_length=7)),
                ('minor_upset_stomach', models.CharField(max_length=7)),
                ('check_for_rashes', models.CharField(max_length=7)),
                ('clinic_services_electronic_signature', models.CharField(max_length=50)),
                ('clinic_services_checkbox', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ClinicServicesOptOut',
        ),
        migrations.DeleteModel(
            name='HealthScreeningsOptOut',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='fam_1_email',
            new_name='fam_1_parent_1_email',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_1_name',
            new_name='pickup_5_name',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_1_phone',
            new_name='pickup_5_phone',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_1_relationship',
            new_name='pickup_5_relationship',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_2_name',
            new_name='pickup_6_name',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_2_phone',
            new_name='pickup_6_phone',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_2_relationship',
            new_name='pickup_6_relationship',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_3_name',
            new_name='pickup_7_name',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_3_phone',
            new_name='pickup_7_phone',
        ),
        migrations.RenameField(
            model_name='emergencycontactinfo',
            old_name='pickup_3_relationship',
            new_name='pickup_7_relationship',
        ),
        migrations.AddField(
            model_name='contactvalidation',
            name='student_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontactinfo',
            name='fam_1_parent_2_email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontactinfo',
            name='student_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaparentchoice',
            name='media_choice_checkbox',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaparentchoice',
            name='media_choice_electronic_signature',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaparentchoice',
            name='student_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalneeds',
            name='student_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactvalidation',
            name='parent_id_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='emergencycontactinfo',
            name='custody_paperwork',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='mediaparentchoice',
            name='media_choice_level',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalneeds',
            name='allergies',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='medicalneeds',
            name='glasses_or_contacts',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='medicalneeds',
            name='hearing_aids',
            field=models.CharField(max_length=7),
        ),
    ]
