# Generated by Django 3.2.5 on 2021-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlane',
            name='alias',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='distributionlane',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='distributionstatus',
            name='alias',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='distributionstatus',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
