# Generated by Django 3.2.5 on 2021-07-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0002_auto_20210720_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionlane',
            options={'verbose_name': 'Distribution Lane', 'verbose_name_plural': 'Distribution Lanes'},
        ),
        migrations.AlterModelOptions(
            name='distributionqueue',
            options={'verbose_name': 'Distribution Queue', 'verbose_name_plural': 'Distribution Queue'},
        ),
        migrations.AlterModelOptions(
            name='distributionstatus',
            options={'verbose_name': 'Distribution Status', 'verbose_name_plural': 'Distribution Statuses'},
        ),
    ]
