# Generated by Django 3.2.5 on 2021-07-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0003_auto_20210720_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionqueue',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modes.distributionstatus'),
        ),
    ]
