# Generated by Django 3.2.5 on 2021-07-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_calendlyevent_event_name'),
        ('modes', '0004_alter_distributionqueue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionqueue',
            name='bpi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device'),
        ),
    ]
