# Generated by Django 3.2.5 on 2021-07-22 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modes', '0008_alter_distributionqueue_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlane',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
