# Generated by Django 3.2.5 on 2021-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0009_alter_distributionlane_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlane',
            name='trouble',
            field=models.BooleanField(default=0),
        ),
    ]
