# Generated by Django 3.2.5 on 2021-09-20 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modes', '0010_distributionlane_trouble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlane',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
