# Generated by Django 3.2 on 2021-05-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_personprograms_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='is_remote',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='is_remote',
            field=models.BooleanField(default=0),
        ),
    ]
