# Generated by Django 3.2 on 2021-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210511_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
