# Generated by Django 3.2.3 on 2021-06-23 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210601_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyAppointment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
