# Generated by Django 3.2.5 on 2021-07-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_calendlyevents_calendlyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlyevent',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
