# Generated by Django 3.2.8 on 2021-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_calendlyevent_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCode',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Location Code',
                'verbose_name_plural': 'Location Codes',
                'ordering': ['id'],
            },
        ),
    ]
