# Generated by Django 4.0a1 on 2021-11-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_devicehistorydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistorydata',
            name='author_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
