# Generated by Django 3.2 on 2021-05-06 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprograms',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(1980, 1, 1, 8, 0), verbose_name='Expiration Date'),
        ),
    ]
