# Generated by Django 3.2.5 on 2021-07-09 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_calendlyappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyEvents',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('event_id', models.CharField(max_length=36, unique=True)),
                ('event_start', models.DateTimeField(null=True)),
                ('event_end', models.DateTimeField(null=True)),
            ],
        ),
    ]
