# Generated by Django 3.2.5 on 2021-07-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_calendlyevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendlyEvents',
            new_name='CalendlyEvent',
        ),
    ]
