# Generated by Django 4.0a1 on 2021-11-02 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_delete_historicalcharger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistoryData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=75, null=True)),
                ('author_username', models.CharField(blank=True, max_length=50, null=True)),
                ('author_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_type', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
