# Generated by Django 3.2.8 on 2022-05-18 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20220201_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprograms',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(1980, 1, 1, 8, 0), verbose_name='Begin Date'),
        ),
    ]
